on:
  push:
    paths:
    - 'hw01.Rmd'
name: Check Rmd Structure
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-bspm:20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Packages
      run: |
        install2.r magrittr
        installGithub.r rundel/parsermd rundel/checklist
    - name: Check Structure
      run: |
        library(parsermd)
        library(magrittr)

        tmpl = parse_rmd("https://raw.githubusercontent.com/rundel/parsermd-hw01/master/hw01.Rmd") %>%
          rmd_subset(rmd, sec_refs = c("Exercise *", "Solution")) %>%
          rmd_subset(sec_refs = c("Exercise 3", "Solution"), type_refs = "rmd_markdown", exclude = TRUE) %>%
          rmd_template(keep_content = TRUE)

        checklist::quit_on_failure({
          parsermd::rmd_check_template("hw01.Rmd", tmpl)
        })
      shell: Rscript {0}
